config/routes.rb
Bookstore::Application.routes.draw do

  resources :roles

  devise_for :admins, :controllers => { :sessions => "admins/sessions" }

  devise_for :users, :path => "usuarios", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
  devise_for :models

  resources :users

  resources :lendbooks

  resources :books

  resources :employees

  resources :departments

  get "home/index"
  root :to => "home#index"

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :department
  attr_accessible :gender, :name ,:department  ,:department_id
  #accepts_nested_attributes_for :department
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new
    @department = Department.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee, :html => {:class => 'form-horizontal'}) do |f| %>
    <% if @employee.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>
          <ul>
            <% @employee.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :gender, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :gender, [["男", 1], ["女", 2], ["保密", 3]], :class => 'select_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :department_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :department_id, Department.all.collect { |p| [p.name, p.id] }, :class => 'select_field' %>
      </div>
    </div>
    <div class="form-actions">
      <%= f.submit :class => 'btn btn-primary' %>
    </div>

<% end %>

app/views/employees/edit.html.erb
<h1>编辑人员</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1>人员清单</h1>
</div>
<%= link_to '新建人员', :controller => "employees", :action => "new" , :class => 'btn   btn-primary'  %>

<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>

    <th>姓名</th>
    <th>性别</th>
    <th>部门</th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>

  <tbody>
  <% @employees.each do |employee| %>
      <tr>
        <td><%= link_to employee.id, employee_path(employee) %></td>

        <td><%= employee.name %></td>
        <td>

          <% ["男", "女", "保密"].each_with_index do |content, index| %>
              <% if (index+1).to_s==employee.gender then %>
                    <%= content %>
              <% end %>
          <%end%>
        </td>
        <td><%= employee.department.name %></td>
        <td><%= link_to '查看', employee , :class => 'btn btn-mini '%>
          <%= link_to '编辑', edit_employee_path(employee) , :class => 'btn btn-mini '%>
          <%= link_to '删除', employee, method: :delete, data: {confirm: '确认么?'} , :class => 'btn btn-mini btn-danger'%></td>
      </tr>
  <% end %>
</table>

app/views/employees/new.html.erb
<h1>新员工</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<div class="page-header">
  <h1>人员管理</h1>
  <p id="notice"><%= notice %></p>
</div>

<dl class="dl-horizontal">
  <dt><strong>姓名:</strong></dt>
  <dd><%= @employee.name %></dd>

  <dt><strong>性别:</strong></dt>
  <dd>
    <% ["男", "女", "保密"].each_with_index do |content, index| %>
        <% if (index+1).to_s==@employee.gender then %>
            <%= content %>
        <% end %>
    <%end%>
  </dd>

  <dt><strong>部门:</strong></dt>
  <dd><%= @employee.department.name %></dd>
</dl>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              employees_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_employee_path(@employee), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              employees_path(@employee),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>