config/routes.rb
Bookstore::Application.routes.draw do

  resources :roles

  devise_for :admins, :controllers => { :sessions => "admins/sessions" }

  devise_for :users, :path => "usuarios", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
  devise_for :models

  resources :users

  resources :lendbooks

  resources :books

  resources :employees

  resources :departments

  get "home/index"
  root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me ,:role_ids
  # attr_accessible :title, :body

  has_and_belongs_to_many :roles
  def role?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @user }
    end
  end

  def new
    @user = User.new
    @current_method = "new"

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, :html => {:class => 'form-horizontal'}) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :email, :class => 'text_field' %>
      </div>
    </div>



    <% if @current_method == "new" %>
        <div class="control-group">
          <%= f.label :password, :class => 'control-label' %>
          <div class="controls">
            <%= f.password_field :password, :class => 'password_field' %>
          </div>
        </div>


        <div class="control-group">
          <%= f.label :password_confirmation, :class => 'control-label' %>
          <div class="controls">
            <%= f.password_field :password_confirmation, :class => 'password_field' %>
          </div>
        </div>


    <% end %>
    <div class="control-group">
      <% for role in Role.find(:all) %>
          <div class="controls">
            <%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role), :class => 'check_box_field' %>
            <%= role.name %>

          </div>
      <% end %>
      </div>
    <div class="form-actions">
      <%= f.submit :class => 'btn btn-primary' %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>编辑用户信息</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1>用户管理</h1>
</div>
<%= link_to '创建新用户', :controller => "users", :action => "new" , :class => 'btn   btn-primary'  %>

<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>

    <th>邮件</th>
    <th>角色</th>
    <th><%= t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>

  <tbody>


  <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>

        <td><%= user.email %></td>
        <td>

          <% for role in user.roles %>
                <%= role.name %>
          <% end %>

        </td>
        <td><%= link_to '查看', user , :class => 'btn btn-mini '%>
          <%= link_to '编辑', edit_user_path(user) , :class => 'btn btn-mini '%>
          <%= link_to '删除', user, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-mini btn-danger' %></td>
      </tr>
  <% end %>

</table>

<br/>

app/views/users/new.html.erb
<h1>创建用户</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="page-header">
  <h1>用户管理</h1>
  <p id="notice"><%= notice %></p>
</div>

<dl class="dl-horizontal">
  <dt><strong>Email:</strong></dt>
  <dd><%= @user.email %></dd>

  <dt><strong>角色:</strong></dt>
  <dd>
    <% for role in @user.roles %>
        <%= role.name %>
    <% end %>
  </dd>
</dl>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              users_path(@user),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>